### ISSUE TITLE
文档部分文字错误

### ISSUE THREAD

**Issue by whace** [ballcat-projects/ballcat-doc#2]
# 快速搭建

## 服务端准备

当然把这些配置全部都放在 application.yml 中也是可以的，但是这样在~~不通~~-->不同 环境下发布时需要不断的修改配置

# 更新日志

## [0.5.0] 2021-12-03

【修改】 `FileService` ，OssClient 不再为必须依赖，当没有配置 Oss 时，默认回退使用 FileClient，根据配置走本地存储或者

这个**或者**后面是不是缺东西，还是多打的

## [0.1.0] 2021-06-28

![image](https://user-images.githubusercontent.com/20571798/147381812-70913877-ae8b-4a00-b4ac-41e7b18202d0.png)

 应更改为 ~~2.4.1 to 2.4.1~~ --> 2.4.1 to 2.4.2 

### Dependency

- Bump spring-boot-admin from 2.4.0 to 2.3.1

降级了吗，是不是为 ~~2.4.0 to 2.3.1~~ --->  2.4.0 to 2.3.1

# redis工具
### 简易分布式锁
![image](https://user-images.githubusercontent.com/20571798/147381898-1d44aa11-a861-4491-8728-422cd091ce28.png)

但是 ~~并为~~ --> 并未 提供锁的续期机制

**Comment by Hccake** [comment]
0.9.0 的时候由于 SBA 的一个登录重定向 bug，所以降级了 SBA 的版本 到 2.3.1 。

0.1.0 的时候又从 2.3.1 升级到 2.4.1
